- name: Install System Packages 1
  become: true
  apt:
    name: ["build-essential", "sway", "xwayland", "wl-clipboard", "dmenu", "unzip", "curl", "fzf", "ripgrep", "udisks2"]
  tags:
    - core

- name: Install System Packages 2
  become: true
  apt:
    name: ["swaylock", "swayidle"]
  tags:
    - core

- name: Neovim Build
  become: true
  apt:
    name: ["ninja-build", "gettext", "cmake"]
  tags:
    - neovim
