- name: Install stow
  apt: name=stow
  tags:
    - dotfiles
- name: Cloning .dotfiles
  become_user: newt
  ansible.builtin.git:
    repo: 'git@github.com:itsnewtjam/.dotfiles.git'
    dest: "~/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
- name: Stow dotfiles
  become_user: newt
  shell: cd ~/.dotfiles && ./debian
  tags:
    - dotfiles
