- name: Install stow
  apt: name=stow
  tags:
    - dotfiles
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:itsnewtjam/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./debian
  tags:
    - dotfiles
